//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageBusinessFront
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocios()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Rubro { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string CUIT { get; set; }
        public string CondicionIVA { get; set; }
        public string RazonSocial { get; set; }
        public System.DateTime FechaInicioActividades { get; set; }
        public int AntiguedadEnRubro { get; set; }
        public string Calle { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
